id: DE45DEDDA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:40:27+00:00'
last_modified: '2022-05-26T12:51:02.201777+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '6202':
      image_group_id: I1PD95884
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1625
      order: 39
      base_file: 6202.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
