id: P588C399E
initial_creation_type: ocr
source_metadata:
  volumes:
    09e7b440353c4a108d04eabb95345dbd:
      base_file: v039.txt
      image_group_id: I1PD95884
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1625
      volume_number: 39
